name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Change to the version you're using, e.g., '14' or '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATICWEBAPPS_API_TOKEN }}  # Your deployment token
          app_location: '/'  # Root location of your app
          api_location: 'api'  # Set to 'api' if you have an API folder, otherwise leave empty
          output_location: 'build'  # Output location of your built app
